#!/bin/bash
# -*- mode: shell-script; -*-
# Time-stamp: <2019-03-18 15:41:26 i337146>
# Usage: add "source /path/bashrcWcf in ~/.bashrc. Note: bashrcWcf need not to be executable."

# Suppress the annoying output.
pushd () {
    command pushd "$@" > /dev/null
}
popd () {
    command popd "$@" > /dev/null
}

w_run() {
  number=$1
  shift
  for i in `seq $number`; do
    $@
  done
}
export w_run
# Example: w_run 4 echo "Hehe"

# bash checks the window size after each command and, if necessary, updates the values of LINES and COLUMNS.
shopt -s checkwinsize
shopt -s cmdhist
# Do not record duplicate commands, ls, bg, fg and exit.
export HISTIGNORE="&:ls:[bf]g:exit"

# shopt -u 

export GITAWAREPROMPT=~/wcfShells/bashScripts
source "${GITAWAREPROMPT}/main.sh"

# The $PWD must be capitalized and the $ must be escaped, otherwise the $PWD will be evaluated where the PS1 is assigned, and then the PS1 will always show the home directory.
# export PS1="\u@\h:\w " # student-mini09:~ wangcf$ command...
# [] will cause problem in PS.
# export PS1="\u@\h:\w/| "
export PS1="\u@\h:\w \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\] "

# Use emacs as default Editor instead of vim.
# export EDITOR=emacs

# alias open="xdg-open"
# export open

export PATH=$PATH:~/bin
# export TERM='xterm-color';

# Set CVSROOT for cvs.
# export CVSROOT=/picb/topaln/cvsroot
# export cvsLocal=~/cvsLocal/TOPALIGN/TAVIEWER
# alias cdcl="cd $cvsLocal" # cd cvsLocal.
# export cdcl
# Set svn.
# export svnRoot="file:///picb/patterns/wangcf/svnRoot"

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' || "$unamestr" == 'Darwin' ]]; then
   platform='freebsd'
fi

if [[ $platform == 'linux' ]]; then
   alias ls='ls --color=auto'
elif [[ $platform == 'freebsd' ]]; then
   alias ls='ls -G'
fi
# alias ls='ls --color'
# alias ls='ls -G'
export ls

alias rm='rm -ir'
export rm
alias rmf='rm -fr'
export rmf
alias cp='cp -ir'
export cp
alias mv='mv -i'
export mv
alias ll='ls -al|less'
export ll
alias scp='scp -r'
export scp

# export projects=/Users/Shared/wangcf/Projects
# export projects="$HOME/patterns/svrBase/projects"
# alias cdp="cd $projects"
# alias cddoc="cd /Users/Shared/wangcf/docs"
# alias cdstu="cd /Users/Shared/wangcf/study"
# alias cdbug='cd build/Debug'
# alias cdw='cd /Users/Shared/wangcf'
# export cdp
# export cddoc
# export cdstu
# export cddebug
# export cdw
